export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME;

export const {NODE_ENV, MONGODB_URI, NEXTAUTH_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, EMAIL_USER, EMAIL_PASS, BASE_URL, TOKEN_EXPIRY} = process.env;
